name: pizza_app_admin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.7.2
  url_strategy: ^0.3.0
  firebase_core: ^3.11.0
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  equatable: ^2.0.7
  font_awesome_flutter: ^10.8.0
  image_picker: ^1.1.2
  image_cropper: ^9.0.0
  supabase_flutter: ^2.8.3
  flutter_dotenv: ^5.2.1
  user_repository:
    path: packages/user_repository
  pizza_repository:
    path: packages/pizza_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
