name: pizza_repository
description: "The Repo that handles pizzas"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.3
  firebase_auth: ^5.4.2
  rxdart: ^0.28.0
  uuid: ^4.5.1
  supabase_flutter: ^2.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
